FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    && rm -rf /var/lib/apt/lists/*

COPY backend/ ./backend/
COPY pcart/ ./pcart/

WORKDIR /app/backend
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir flask flask-cors gunicorn

EXPOSE 5000

RUN mkdir -p ./data/venv ./data/projects ./data/fixed_projects

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "2", "run:app"]